### PR TITLE
Font accessibility

### PR DESCRIPTION
**Pull request by zone-live**
Changed font unit from 'px' to 'em' and Increased its size to 1.1em.

### CODE REVIEW

**Comment by benschwarz** [comment]
Any chance of a screen shot before we merge this? Even just inspecting on the existing site is fine

**Comment by zone-live** [comment]
Here it is http://monosnap.com/image/UzOxqnG2MRxwtqSm8gPlco2oRDZrzs

**Comment by benschwarz** [comment]
Thanks !

**Comment by PowerWebsite** [comment]
I want

**Pull request merged**
